# Generated by Django 4.1.4 on 2023-02-10 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Профайл прошел модерацию')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Логотип')),
                ('company_name', models.CharField(default='No name', max_length=100, verbose_name='Наименование компании')),
                ('legal_entity', models.CharField(blank=True, max_length=100, verbose_name='Юридическое лицо')),
                ('company_address', models.CharField(default='Some address', max_length=255, verbose_name='Адрес компании')),
                ('email', models.EmailField(blank=True, max_length=128, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('about_company', models.CharField(blank=True, max_length=512, verbose_name='О компании')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Вакансия прошла модерацию')),
                ('vacancy_name', models.CharField(db_index=True, default='SOME STRING', max_length=300)),
                ('city', models.CharField(db_index=True, default='', max_length=100, verbose_name='Город размещения')),
                ('duties_description', models.TextField(blank=True, verbose_name='Обязанности')),
                ('requirements_description', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('work_conditions', models.TextField(blank=True, null=True, verbose_name='Условия труда')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания вакансии')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная заралата')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальная заралата')),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Открыта')),
                ('is_for_disabled', models.BooleanField(default=False, help_text='Отметьте, вакансия подходит для людей с ограниченными физическими возможностями', verbose_name='Вакансия для людей с инвалидностью')),
                ('is_full_day', models.BooleanField(default=False, help_text='Отметьте, если вакансия полного рабочего дня', verbose_name='Полный рабочий день')),
                ('is_intern', models.BooleanField(default=False, help_text='Отметьте, если вакансия является стажировкой', verbose_name='Cтажировка')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.companyprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
