# Generated by Django 4.1.4 on 2023-02-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, unique=True, verbose_name='Заголовок новости')),
                ('link', models.CharField(max_length=2048, unique=True, verbose_name='Ссылка на новость')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание новости')),
            ],
        ),
    ]
