# Generated by Django 4.1.4 on 2023-02-10 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Резюме прошло модерацию')),
                ('moving', models.CharField(choices=[('PO', 'возможен'), ('IM', 'невозможен'), ('UN', 'нежелателен')], default='IM', max_length=2, verbose_name='Возможен ли переезд')),
                ('business_trips', models.CharField(choices=[('NR', 'не готов'), ('RE', 'готов'), ('SO', 'не частые командировки')], default='NR', max_length=2, verbose_name='Командировки')),
                ('desired_position', models.CharField(blank=True, max_length=180, verbose_name='Желаемая должность')),
                ('salary', models.IntegerField(blank=True, verbose_name='Зарплата')),
                ('busyness', models.CharField(choices=[('FE', 'полная занятость'), ('PE', 'частичная занятость'), ('PW', 'проектная работа'), ('V', 'волонтерство'), ('I', 'стажировка')], default='FE', max_length=5, verbose_name='Варниант занятости')),
                ('work_schedule', models.CharField(choices=[('FD', 'полный день'), ('SS', 'сменный график'), ('FS', 'гибкий график'), ('DW', 'удаленная работа')], default='FD', max_length=5, verbose_name='График работы')),
                ('getting_started', models.DateField(verbose_name='Начало работы')),
                ('end_work', models.DateField(verbose_name='Окончание работы')),
                ('working', models.BooleanField(default=False, verbose_name='Работаю по настоящее время')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='Организация')),
                ('post', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Обязанности на рабочем месте')),
                ('skills', models.TextField(blank=True, verbose_name='Ключевые навыки')),
                ('about_me', models.TextField(blank=True, verbose_name='О себе')),
                ('level', models.CharField(choices=[('SE', 'Среднее'), ('SSE', 'Среднее специальное'), ('IHE', 'Неоконченное высшее'), ('HE', 'Высшее'), ('BE', 'Бакалавр'), ('ME', 'Магистр'), ('CSE', 'Кандидат наук'), ('DSE', 'Доктор наук')], default='SE', max_length=3, verbose_name='Образование')),
                ('educational_institution', models.CharField(blank=True, max_length=150, verbose_name='Учебное заведение')),
                ('faculty', models.CharField(blank=True, max_length=150, verbose_name='Факультет')),
                ('specialization', models.CharField(blank=True, max_length=150, verbose_name='Специализация')),
                ('year_graduation', models.DateField(verbose_name='Год окончания')),
                ('course_name', models.CharField(blank=True, max_length=150, verbose_name='Название курса')),
                ('organization_conducted', models.CharField(blank=True, max_length=150, verbose_name='Проводившая организация')),
                ('specialization_course', models.CharField(blank=True, max_length=150, verbose_name='Специализация')),
                ('year_graduation_course', models.DateField(verbose_name='Год окончания')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец резюме')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
